import { useMemo } from 'react';
import { Link, useLocation, useNavigate, useParams } from 'react-router-dom';
import { ArrowLeft, Clock, ExternalLink, FileText, ListChecks, MapPin, RefreshCw, Sparkles, Tags, Users, Zap } from 'lucide-react';
import { newsApi } from '../../api/news';
import { Banner, Button, Card, CardHeader, EmptyState, LinkButton } from '../../components/ui';
import { BreakingPill, CategoryBadge, TopicBadge, TrendingPill } from '../../components/news/Badges';
import { NewsImage } from '../../components/news/NewsCard';
import { CoverageList, MoreLikeThis } from '../../components/news/RelatedStories';
import { useApi } from '../../hooks/useNews';
import { useDocumentTitle } from '../../hooks/useDocumentTitle';
import { formatDateTime, isTrending, safeHref, sourceCount, timeAgo } from '../../utils/news';

function DetailSkeleton() {
  return (
    <div className="stack" aria-hidden="true">
      <div className="skeleton" style={{ height: 34, width: '70%' }} />
      <div className="skeleton" style={{ height: 300, borderRadius: 16 }} />
      <div className="skeleton" style={{ height: 160, borderRadius: 12 }} />
    </div>
  );
}

const SUMMARY_LABEL = {
  ai: ['AI summary', 'Generated by AI from the headline and the publisher\'s teaser only.'],
  extractive: ['Summary', 'The opening of the publisher\'s own teaser. AI summary not generated for this article.'],
};

export default function NewsDetail() {
  const { id } = useParams();
  const navigate = useNavigate();
  const location = useLocation();
  const article = useApi((s) => newsApi.article(id, s), [id]);
  const a = article.data;
  const gid = a?.duplicate_group_id;
  const story = useApi((s) => (gid ? newsApi.story(gid, s) : Promise.resolve(null)), [gid]);
  const related = useApi((s) => (a ? newsApi.related(id, 8, s) : Promise.resolve([])), [id, Boolean(a)]);
  useDocumentTitle(a?.title || 'News');

  const more = useMemo(() => (related.data || []).filter((r) => r.duplicate_group_id !== gid).slice(0, 4), [related.data, gid]);
  const back = () => (location.key !== 'default' ? navigate(-1) : navigate('/news'));

  const backBtn = (
    <button type="button" className="ev-back nw-back" onClick={back}>
      <ArrowLeft size={16} aria-hidden="true" /> Back to News
    </button>
  );

  if (article.loading && !a) return <>{backBtn}<DetailSkeleton /></>;
  if (article.error && !a) {
    const missing = /not found/i.test(article.error);
    return (
      <>
        {backBtn}
        {missing ? (
          <EmptyState icon={FileText} title="Story not found" action={<LinkButton to="/news">Browse the news</LinkButton>}>
            This story may have been removed to keep the archive fresh. Older stories are cleared automatically.
          </EmptyState>
        ) : (
          <Banner tone="error" title="Unable to load this story" action={<Button size="sm" variant="secondary" icon={RefreshCw} onClick={article.reload}>Try again</Button>}>
            {article.error}
          </Banner>
        )}
      </>
    );
  }

  const original = safeHref(a.url);
  const [summaryTitle, summaryNote] = SUMMARY_LABEL[a.summary_source] || ['Summary', ''];
  const detail = a.entities_detail || {};
  const people = detail.people || [];
  const orgs = detail.organizations || [];
  const places = a.location || [];
  const count = sourceCount(a);
  const summaryText = a.summary || a.description;

  return (
    <article className="nw-detail">
      {backBtn}

      <header className="nw-detail__head">
        <div className="nw-detail__badges">
          {a.is_breaking && <BreakingPill />}
          {isTrending(a) && !a.is_breaking && <TrendingPill />}
          <CategoryBadge slug={a.category} />
          {(a.categories || []).filter((c) => c !== a.category).slice(0, 2).map((c) => <CategoryBadge key={c} slug={c} />)}
        </div>
        <h1>{a.title}</h1>
        <div className="nw-detail__meta">
          <span><strong>{a.source?.name}</strong></span>
          <span aria-hidden="true">·</span>
          <span className="row" style={{ gap: 6 }}><Clock size={14} aria-hidden="true" /><time dateTime={a.published_at}>{formatDateTime(a.published_at)}</time> <span className="muted">({timeAgo(a.published_at)})</span></span>
          {count > 1 && <><span aria-hidden="true">·</span><span>Covered by <strong>{count} sources</strong></span></>}
        </div>
      </header>

      <div className="nw-detail__grid">
        <div className="stack stack--lg">
          {a.image_url && (
            <figure className="nw-detail__figure">
              <NewsImage src={a.image_url} category={a.category} className="nw-detail__img" size={50} />
              <figcaption>Image: {a.source?.name}</figcaption>
            </figure>
          )}

          <Card as="section" accent aria-labelledby="sum-h">
            <CardHeader icon={Sparkles} title={summaryTitle} actions={summaryNote ? <span className="nw-note" title={summaryNote}>{a.summary_source === 'ai' ? 'AI-generated' : 'From publisher'}</span> : null} />
            {summaryText ? <p className="nw-detail__summary" id="sum-h">{summaryText}</p> : <p className="muted">No summary is available for this story. Use the link to read the original article.</p>}
            {summaryNote && <p className="text-xs muted" style={{ marginTop: 10 }}>{summaryNote}</p>}
          </Card>

          {a.event && (
            <Card as="section">
              <CardHeader icon={Zap} title="What happened?" />
              <p className="field-value">{a.event}</p>
            </Card>
          )}

          {a.key_points?.length > 0 && (
            <Card as="section">
              <CardHeader icon={ListChecks} title="Key points" />
              <ul className="nw-keypoints">{a.key_points.map((k, i) => <li key={i}>{k}</li>)}</ul>
            </Card>
          )}

          {(a.topics?.length > 0 || people.length + orgs.length + places.length > 0) && (
            <Card as="section">
              {a.topics?.length > 0 && (
                <>
                  <CardHeader icon={Tags} title="Topics" />
                  <div className="nw-topics">{a.topics.map((t) => <TopicBadge key={t} topic={t} />)}</div>
                </>
              )}
              {people.length + orgs.length > 0 && (
                <>
                  <h3 className="subhead"><Users size={13} aria-hidden="true" style={{ verticalAlign: '-2px' }} /> People &amp; organisations</h3>
                  <div className="nw-topics">
                    {[...people, ...orgs].map((e) => <Link key={e} to={`/news?q=${encodeURIComponent(e)}`} className="nw-entity">{e}</Link>)}
                  </div>
                </>
              )}
              {places.length > 0 && (
                <>
                  <h3 className="subhead"><MapPin size={13} aria-hidden="true" style={{ verticalAlign: '-2px' }} /> Places</h3>
                  <div className="nw-topics">{places.map((p) => <Link key={p} to={`/news?q=${encodeURIComponent(p)}`} className="nw-entity">{p}</Link>)}</div>
                </>
              )}
            </Card>
          )}

          <CoverageList articles={story.data?.articles} currentId={a.id} />
          <MoreLikeThis articles={more} />
        </div>

        <aside className="nw-detail__aside">
          <Card as="section" aria-label="Original article">
            <div className="field-label">Original article</div>
            <p className="text-sm" style={{ margin: '4px 0 14px' }}>Read the full story on <strong>{a.source?.name}</strong>. Casefile shows a summary and links to the publisher.</p>
            {original ? (
              <a className="btn btn--primary btn--lg" href={original} target="_blank" rel="noopener noreferrer" style={{ width: '100%' }}>
                Read Original Article <ExternalLink size={16} aria-hidden="true" />
              </a>
            ) : (
              <p className="muted text-sm">The original link is unavailable.</p>
            )}
            <p className="text-xs muted" style={{ marginTop: 12 }}>© {a.source?.name}. Headline and teaser are shown for attribution and discovery.</p>
          </Card>
        </aside>
      </div>
    </article>
  );
}
